# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zUhvJpOQEw6tAg33j8gThEE2sjMwht2r
"""



import streamlit as st
import pickle
import string
from nltk.corpus import stopwords
import nltk
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

nltk.download('stopwords')
# text perprocess
def transform_text(text):
  text = text.lower()
  text = nltk.word_tokenize(text)

  y = []
  for char in text:
    if char.isalnum():
      y.append(char)

  text = y[:]
  y.clear()

  for word in text:
    if word not in stopwords.words('english') and word not in string.punctuation:
      y.append(word)
  text = y[:]
  y.clear

  for char in text:
    y.append(ps.stem(char))
  return ' '.join()

tfidf = pickle.load(open('vectorizer.pkl','rb'))
model = pickle.load(open('model_voting.pkl','rb'))

st.title('SMS/Email Spam Classifier')

input_sms  = st.text_area('Enter The Message')

if st.button('Predict'):
  transform_sms = transform_text(input_sms)

  vector_input = tfidf.transform([transform_sms])

  result = model.predict(vector_input)[0]

  if result == 1:
    st.header('Spam')
  else:
    st.header('Not Spam')

