# -*- coding: utf-8 -*-
"""sms spam.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13q2c_IEAIvOMzwOqUYE6_Fp9etv2i7-r
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('/content/spam.csv',encoding = 'latin-1')

df.shape

df.head(5)

df.info()

df.describe()

df.isnull().sum()

# data cleaning
df = df.drop(columns=['Unnamed: 2','Unnamed: 3','Unnamed: 4'])

df.isnull().sum()

df.head()

# renaming the columns name
df = df.rename(columns={'v1':'target','v2':'text'})

df.head()

from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

df['target'] = encoder.fit_transform(df['target'])

df.head()

# checking duplicate
print(df.duplicated().sum())

# droping dupcate values
df = df.drop_duplicates(keep='first')

# EDA
df['target'].value_counts()

# target column is imbalance
df['target'].value_counts().plot(kind='pie',figsize=(5,5),autopct='%1.1f%%')

import nltk

nltk.download('punkt')
nltk.download('punkt_tab')

# number of characters every sms
df['num_characters']=df['text'].apply(len)

df.head()

# number of words
df['num_words'] = df['text'].apply(lambda x:len(nltk.word_tokenize(x)))

df.head()

# number of sentences
df['num_sentences'] = df['text'].apply(lambda x:len(nltk.sent_tokenize(x)))

df.head()

df[['num_characters',	'num_words'	,'num_sentences']].describe()

# for ham
df[df['target']==0][['num_characters'	,'num_words',	'num_sentences']].describe()

# for spam
df[df['target']==0][['num_characters'	,'num_words',	'num_sentences']].describe()

plt.figure(figsize=(12,6))
sns.histplot(df[df['target']==0]['num_characters'])
sns.histplot(df[df['target']==1]['num_characters'],color='red')

sns.pairplot(df,hue='target')

df.corr(numeric_only = True)

sns.heatmap(df.corr(numeric_only = True),annot=True)

from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
import string

import nltk
nltk.download('stopwords')

# Data preprocessing
def transform_text(text):
  # conver lower
  text = text.lower()
  # devied into token
  text = nltk.word_tokenize(text)
  # remove special characters
  y = []
  for char in text:
    if char.isalnum():
      y.append(char)

  text = y[:]
  y.clear()

  for char in text:
    if char not in stopwords.words('english') and char not in string.punctuation:
      y.append(char)

  text = y[:]
  text.clear()
  for char in text:
    y.append(PorterStemmer().stem(char))

  return " ".join(y)

  return text

transform_text('I loved the YT lacture on Machiine learing. how about you?')

df['transformed_text'] = df['text'].apply(transform_text)

df.head()

from wordcloud import WordCloud
wc = WordCloud(width=500,height=500,min_font_size=10,background_color='white')

spam_wc = wc.generate(df[df['target']==1]['transformed_text'].str.cat(sep=' '))

plt.imshow(spam_wc)

ham_wc = wc.generate(df[df['target']==0]['transformed_text'].str.cat(sep=' '))

plt.imshow(ham_wc)

spam_corpus = []
for msg in df[df['target']==1]['transformed_text'].tolist():
  for word in msg.split():
    spam_corpus.append(word)

len(spam_corpus)

df.head()

# model bulding
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

X = cv.fit_transform(df['transformed_text']).toarray()

X.shape

y = df['target'].values

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state = 2)

from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score

gnb = GaussianNB()
mnb = MultinomialNB()
bnb = BernoulliNB()

# GaussianNB
gnb.fit(X_train,y_train)
y_pred1 = gnb.predict(X_test)
print(accuracy_score(y_test,y_pred1))
print(confusion_matrix(y_test,y_pred1))
print(precision_score(y_test,y_pred1))

# multinomial NB
mnb.fit(X_train,y_train)
y_pred2 = mnb.predict(X_test)
print(accuracy_score(y_test,y_pred2))
print(confusion_matrix(y_test,y_pred2))
print(precision_score(y_test,y_pred2))

# BernoulliNB
bnb.fit(X_train,y_train)
y_pred3 = bnb.predict(X_test)
print(accuracy_score(y_test,y_pred3))
print(confusion_matrix(y_test,y_pred3))
print(precision_score(y_test,y_pred3))

# TfidfVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()

X_tfidf = tfidf.fit_transform(df['transformed_text']).toarray()

X_train_tfidf,X_test_tfidf,y_train_tfidf,y_test_tfidf = train_test_split(X_tfidf,y,test_size=0.2,random_state = 2)

# GaussianNB
gnb.fit(X_train_tfidf,y_train_tfidf)
y_pred1_tfidf = gnb.predict(X_test_tfidf)
print(accuracy_score(y_test,y_pred1_tfidf))
print(confusion_matrix(y_test,y_pred1_tfidf))
print(precision_score(y_test,y_pred1_tfidf))

# BornualliNB
bnb.fit(X_train_tfidf,y_train_tfidf)
y_pred2_tfidf = bnb.predict(X_test_tfidf)
print(accuracy_score(y_test,y_pred2_tfidf))
print(confusion_matrix(y_test,y_pred2_tfidf))
print(precision_score(y_test,y_pred2_tfidf))

# MultinuallimalNNNB
mnb.fit(X_train_tfidf,y_train_tfidf)
y_pred3_tfidf = mnb.predict(X_test_tfidf)
print(accuracy_score(y_test,y_pred3_tfidf))
print(confusion_matrix(y_test,y_pred3_tfidf))
print(precision_score(y_test,y_pred3_tfidf))

# tfidf and mnb

# try more model to find best
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier

svc = SVC(kernel='sigmoid',gamma=1.0)
knc = KNeighborsClassifier()
mnb = MultinomialNB()
dtc = DecisionTreeClassifier(max_depth=5)
lrc = LogisticRegression(solver='liblinear',penalty='l1')
rfc = RandomForestClassifier(n_estimators=50,random_state=2)
abc = AdaBoostClassifier(n_estimators=50,random_state=2)
bc = BaggingClassifier(n_estimators=50,random_state=2)
etc = ExtraTreesClassifier(n_estimators=50,random_state=2)
gbdt = GradientBoostingClassifier(n_estimators=50,random_state=2)
xgb = XGBClassifier(n_estimators=50,random_state=2)

clfs = {
    'SVC' : svc,
    'KN' : knc,
    'NB': mnb,
    'DT': dtc,
    'LR': lrc,
    'RF': rfc,
    'AdaBoost': abc,
    'BgC': bc,
    'ETC': etc,
    'GBDT':gbdt,
    'xgb':xgb

}

def train_classifier(clf,X_train,y_train,X_test,y_test):
  clf.fit(X_train,y_train)
  y_pred = clf.predict(X_test)
  accuracy = accuracy_score(y_test,y_pred)
  precision = precision_score(y_test,y_pred)

  return accuracy,precision

accuracy_scores = []
precision_scores = []

for name,clf in clfs.items():
  current_accuracy,current_precision = train_classifier(clf,X_train,y_train,X_test,y_test)
  print(f'{name} accuracy is {current_accuracy}')
  print(f'{name} precision is {current_precision}')

  accuracy_scores.append(current_accuracy)
  precision_scores.append(current_precision)

performance_df = pd.DataFrame({'Algorithm':clfs.keys(),'Accuracy':accuracy_scores,'Precision':precision_scores}).sort_values('Precision',ascending=False)

performance_df

# model imporve
from sklearn.ensemble  import VotingClassifier

"""# appling voting

"""

voting = VotingClassifier(estimators=[('RFC',rfc),('ETC',etc),('LR',lrc)],voting='soft')

voting.fit(X_train,y_train)

y_pred = voting.predict(X_test)
print('Accuracy',accuracy_score(y_test,y_pred))
print('Precision',precision_score(y_test,y_pred))

"""# appling stacking"""

estimators = [('RFC',rfc),('ETC',etc),('LR',lrc)]
final_estimator = RandomForestClassifier()

from sklearn.ensemble import StackingClassifier

clf = StackingClassifier(estimators=estimators,final_estimator=final_estimator)

clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)
print('Accuracy',accuracy_score(y_test,y_pred))
print('Precision',precision_score(y_test,y_pred))

import pickle
pickle.dump(tfidf,open('vectorizer.pkl','wb'))
pickle.dump(mnb,open('model_mnb.pkl','wb'))
pickle.dump(voting,open('model_voting.pkl','wb'))

